version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://db:27017/db_recipes

  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local